package ventanas;


import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Miguel Ruiz
 */
public class PerfilUsuario extends javax.swing.JFrame {

    //VARIABLE PARA IDENTIFICAR EL GENERO DEL USUARIO QUE INICIO SESION.
    String gen = null;

    public PerfilUsuario() {
        initComponents();
        setTitle("Perfil usuario");
        setLocationRelativeTo(null);
        setResizable(false);
//        colocaImgPerfil();
        if(gen=="F"){
            ImageIcon wallpaper = new ImageIcon("src/img/niña.png");
                //Adaptamos la imagen al tamaño del JLabel con la clase ICON.
                Icon wallpaperScaled = new ImageIcon(wallpaper.getImage().getScaledInstance(imgPerfil.getWidth(),
                        imgPerfil.getHeight(), Image.SCALE_DEFAULT));
                //Agregamos la imagen ya escalable al JLabel.
                imgPerfil.setIcon(wallpaperScaled);
                this.repaint();
        }else if(gen=="M"){
            ImageIcon wallpaper = new ImageIcon("src/img/niño.png");
                //Adaptamos la imagen al tamaño del JLabel con la clase ICON.
                Icon wallpaperScaled = new ImageIcon(wallpaper.getImage().getScaledInstance(imgPerfil.getWidth(),
                        imgPerfil.getHeight(), Image.SCALE_DEFAULT));
                //Agregamos la imagen ya escalable al JLabel.
                imgPerfil.setIcon(wallpaperScaled);
                this.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imgPerfil.setMaximumSize(new java.awt.Dimension(128, 128));
        imgPerfil.setMinimumSize(new java.awt.Dimension(128, 128));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(imgPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(imgPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgPerfil;
    // End of variables declaration//GEN-END:variables
}
